name: build-php
description: Build PHP
author: php

branding:
  icon: package
  color: purple

inputs:
  php-version:
    description: PHP version to build
    required: true
  arch:
    description: Architecture to build
    required: true
  ts:
    description: Thread safety to build
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build PHP
      shell: pwsh
      run: |
        Import-Module $pwd\php\BuildPhp -Force
        Invoke-PhpBuild -PhpVersion ${{github.event.inputs.php-version}} `
                        -Arch ${{github.event.inputs.php-version}} `
                        -Ts ${{github.event.inputs.ts}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: artifacts/*
