name: build-php
description: Build PHP
author: php

branding:
  icon: package
  color: purple

inputs:
  php-version:
    description: PHP version to build
    required: true

strategy:
  matrix:
    arch: [x64, x86]
    ts: [nts, ts]

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build PHP
      shell: pwsh
      run: |
        Install-Module php/BuildPhp -Force
        Invoke-PhpBuild -PhpVersion ${{github.event.inputs.php-version}} `
                        -Arch ${{matrix.arch}} `
                        -Ts ${{matrix.ts}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: *
        path: artifacts
