name: Build PHP
on:
  workflow_dispatch:
    inputs:
      php-version:
        description: 'PHP version to build'
        required: true
jobs:
  php:
    strategy:
      matrix:
        arch: [x64, x86]
        ts: [nts, ts]
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./php
        with:
          php-version: ${{ github.event.inputs.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}

  artifacts:
    runs-on: ubuntu-latest
    needs: php
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: artifacts
          merge-multiple: true

      - name: Create artifacts zip for all zip files in artifacts folder
        run: |
          cd artifacts
          zip -r ../artifacts.zip *

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts.zip
          path: artifacts.zip